### ISSUE TITLE
Run ESPEI via input files, rather than command line arguments

### ISSUE THREAD

**Issue by bocklund** [PhasesResearchLab/ESPEI#27]
A first draft and feedback was written in [this gist](https://gist.github.com/bocklund/c87f767c1a29230c90acd600fe39c78e)

The current iteration is:

```yaml
Header area.
Include any metadata above the `---`.
---
# core run settings
run_type: full # choose full | dft | mcmc
phase_models: input.json
datasets: input-datasets # path to datasets. Defaults to current directory.
scheduler: dask # can be dask | MPIPool

# control output
verbosity: 0 # integer verbosity level 0 | 1 | 2, where 2 is most verbose.
output_tdb: out.tdb
tracefile: chain.npy # name of the file containing the mcmc chain array
probfile: lnprob.npy # name of the file containing the mcmc ln probability array

# the following only take effect for full or mcmc runs
mcmc:
  mcmc_steps: 2000
  mcmc_save_interval: 100

  # the following take effect for only mcmc runs
  input_tdb: null # TDB file used to start the mcmc run
  restart_chain: null # restart the mcmc fitting from a previous calculation
```

This issue will focus on the development of a first generation input file structure and spec, and also as a place to brainstorm options that should be user-facing.
